// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Thumbnail struct {
	ID        uuid.UUID
	Src       string
	Video     uuid.UUID
	Timestamp string
	Idx       pgtype.Int4
}

type Video struct {
	ID              uuid.UUID
	Src             string
	ThumbnailsCount int32
	Dur             string
	Thumbnail       pgtype.UUID
}
