// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Thumbnail struct {
	ID        uuid.UUID
	Src       string
	TimeStamp string
	Idx       pgtype.Int4
	Video     uuid.UUID
}

type Video struct {
	ID              uuid.UUID
	Src             string
	ThumbnailsCount int32
	Dur             string
	Thumbnail       pgtype.UUID
}
