// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: thumbnails.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAllThubmsOfVideo = `-- name: GetAllThubmsOfVideo :many
SELECT id, src, time_stamp, idx, video
FROM thumbnails AS t
WHERE t.video = $1
`

func (q *Queries) GetAllThubmsOfVideo(ctx context.Context, video uuid.UUID) ([]Thumbnail, error) {
	rows, err := q.db.Query(ctx, getAllThubmsOfVideo, video)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thumbnail
	for rows.Next() {
		var i Thumbnail
		if err := rows.Scan(
			&i.ID,
			&i.Src,
			&i.TimeStamp,
			&i.Idx,
			&i.Video,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThumb = `-- name: GetThumb :one
SELECT id, src, time_stamp, idx, video FROM thumbnails
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetThumb(ctx context.Context, id uuid.UUID) (Thumbnail, error) {
	row := q.db.QueryRow(ctx, getThumb, id)
	var i Thumbnail
	err := row.Scan(
		&i.ID,
		&i.Src,
		&i.TimeStamp,
		&i.Idx,
		&i.Video,
	)
	return i, err
}

const insertThumbs = `-- name: InsertThumbs :one
INSERT INTO thumbnails(
 src,video,time_stamp,idx
) VALUES ( $1,$2,$3,$4)
RETURNING id, src, time_stamp, idx, video
`

type InsertThumbsParams struct {
	Src       string
	Video     uuid.UUID
	TimeStamp string
	Idx       pgtype.Int4
}

func (q *Queries) InsertThumbs(ctx context.Context, arg InsertThumbsParams) (Thumbnail, error) {
	row := q.db.QueryRow(ctx, insertThumbs,
		arg.Src,
		arg.Video,
		arg.TimeStamp,
		arg.Idx,
	)
	var i Thumbnail
	err := row.Scan(
		&i.ID,
		&i.Src,
		&i.TimeStamp,
		&i.Idx,
		&i.Video,
	)
	return i, err
}
