// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: videos.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO Video(
 src,thumbnails_count,dur
) VALUES ( $1,$2,$3)
RETURNING id, src, thumbnails_count, dur, thumbnail
`

type CreateVideoParams struct {
	Src             string
	ThumbnailsCount int32
	Dur             string
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo, arg.Src, arg.ThumbnailsCount, arg.Dur)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Src,
		&i.ThumbnailsCount,
		&i.Dur,
		&i.Thumbnail,
	)
	return i, err
}

const getVideo = `-- name: GetVideo :one
SELECT id, src, thumbnails_count, dur, thumbnail FROM Video
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetVideo(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Src,
		&i.ThumbnailsCount,
		&i.Dur,
		&i.Thumbnail,
	)
	return i, err
}

const updateVideo = `-- name: UpdateVideo :one
UPDATE Video
  set thumbnail= $2
WHERE id = $1
RETURNING id, src, thumbnails_count, dur, thumbnail
`

type UpdateVideoParams struct {
	ID        uuid.UUID
	Thumbnail pgtype.UUID
}

func (q *Queries) UpdateVideo(ctx context.Context, arg UpdateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, updateVideo, arg.ID, arg.Thumbnail)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Src,
		&i.ThumbnailsCount,
		&i.Dur,
		&i.Thumbnail,
	)
	return i, err
}
